stages:
  - setup
  - quality
  - test
  - build
  - deploy

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache_yarn
    - ${CI_PROJECT_DIR}/packages/frontend/node_modules

image: danlynn/ember-cli:3.1.4

variables:
  YARN_CACHE_FOLDER: .cache_yarn
  DOCKER_DRIVER: overlay2

lint:
  stage: test
  tags: [ docker ]
  dependencies: [ setup ]
  script: [ time ./run yarn lint ]

# TODO: coverage?
test:
  stage: test
  tags: [ docker ]
  dependencies: [ setup ]
  script: [ time ./run yarn test ]


build-production:
  stage: build
  tags: [ docker ]
  dependencies: [ setup ]
  script:
    - time ./run yarn build:production
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/packages/frontend/dist


deploy-production:
  stage: deploy
  tags: [ docker ]
  script:
    - time npm i -g netlify-cli
    - time netlify deploy -s emberclear -p packages/frontend/dist -t $NETLIFY_ACCESS_TOKEN -e production

setup:
  stage: setup
  tags: [ docker ]
  script: [ time ./run yarn install ]
  # artifacts:
  #   paths:
  #     - /usr/local/bin
  #     - ${CI_PROJECT_DIR}/packages/frontend/node_modules/
