---
language: node_js
node_js:
  - "node"
  - "lts/*"

sudo: "required"
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn
    - packages/frontend/node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - yarn config set cache-folder $HOME/.yarn

script:
  # - npm run lint:js
  - cd packages/frontend && rm -rf tmp dist node_modules && yarn && yarn test
