version: '3.4'
services:
  phoenix-relay:
    build:
      context: ./relays/phoenix-relay

    command: bash -c "mix deps.get && mix phx.server"
    container_name: phoenix-relay
    volumes:
      - .:/app
    ports:
      - "4301:4301"
    volumes:
      - phoenix-deps:/app/deps
      - phoenix-build:/app/_build
      - ./relays/phoenix-relay:/app

  emberclear:
    build:
      context: ./frontend

    # Default command to run when the container starts
    command: bash -c "yarn && yarn start:dev -p 4201"

    # To prevent files created in the container from being owned by root
    # to get these numbers: `echo "$(id -u):$(id -g)"`
    # user: 1000:1000

    # A friendly name for finding the container with
    # docker commands easier
    container_name: emberclear

    # NOTE: Ports Mappings are HOST:CONTAINER
    ports:
      # Test Server
      - 7357:7357
      # Ember Dev Server
      - 4201:4201
      # Live Reload
      - 7020:7020
    volumes:
      - ember-tmp:/app/tmp
      - ember-dist:/app/dist
      - ember-node_modules:/app/node_modules
      # Copies the whole app into the container
      # - ./frontend:/app:delegated

      # Copy invidial files/folders so container contents don't leak out
      - ./frontend/config:/app/config
      - ./frontend/fastboot:/app/fastboot
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests
      - ./frontend/translations:/app/translations
      - ./frontend/types:/app/types
      - ./frontend/vendor:/app/vendor

      - ./frontend/.ember-cli:/app/.ember-cli
      - ./frontend/.eslintignore:/app/.eslintignore
      - ./frontend/.eslintrc.js:/app/.eslintrc.js
      - ./frontend/.watchmanconfig:/app/.watchmanconfig
      - ./frontend/ember-cli-build.js:/app/ember-cli-build.js
      - ./frontend/package.json:/app/package.json
      - ./frontend/testem.js:/app/testem.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/yarn.lock:/app/yarn.lock

      # Override the above mapping for the following
      # noise directories:



volumes:
  ember-tmp:
  ember-dist:
  ember-node_modules:
  phoenix-deps:
  phoenix-build:
